import { safeLocalStorage } from "./browser-utils"

export type SocialPlatform =
  | "discord"
  | "notion"
  | "github"
  | "twitter"
  | "youtube"
  | "telegram"
  | "instagram"
  | "twitch"
  | "whatsapp"
  | "facebook"
  | "pinterest"

export type SocialAccount = {
  id: string
  platform: SocialPlatform
  name: string
  avatar?: string
  accessToken?: string
  refreshToken?: string
  expiresAt?: Date
  isConnected: boolean
}

export type SocialPost = {
  id: string
  platform: SocialPlatform
  accountId: string
  author: {
    id: string
    name: string
    avatar?: string
    url?: string
  }
  content: string
  mediaUrls?: string[]
  url?: string
  createdAt: Date
  likes?: number
  shares?: number
  comments?: number
  isBookmarked: boolean
  topics: string[]
  sentiment?: "positive" | "neutral" | "negative"
  metadata: Record<string, any>
}

export type SocialFilter = {
  id: string
  name: string
  platforms: SocialPlatform[]
  keywords: string[]
  authors: string[]
  excludeKeywords: string[]
  excludeAuthors: string[]
  dateRange?: {
    start?: Date
    end?: Date
  }
  sentiment?: ("positive" | "neutral" | "negative")[]
  isActive: boolean
}

export type SocialTopic = {
  id: string
  name: string
  description?: string
  keywords: string[]
  filters: string[]
  isMonitoring: boolean
  notifyOnMatch: boolean
  autoGenerateDrafts: boolean
  lastChecked?: Date
  posts: string[]
}

export type DraftResponse = {
  id: string
  topicId: string
  platform: SocialPlatform
  content: string
  mediaUrls?: string[]
  createdAt: Date
  status: "draft" | "approved" | "rejected" | "published"
  postId?: string
  metadata: Record<string, any>
}

// Local storage keys
const ACCOUNTS_STORAGE_KEY = "flowiseSocialAccounts"
const POSTS_STORAGE_KEY = "flowiseSocialPosts"
const FILTERS_STORAGE_KEY = "flowiseSocialFilters"
const TOPICS_STORAGE_KEY = "flowiseSocialTopics"
const DRAFTS_STORAGE_KEY = "flowiseSocialDrafts"

// Social media service for managing social media integrations
export class SocialMediaService {
  // Get all accounts
  public getAccounts(): SocialAccount[] {
    const accountsJson = safeLocalStorage().getItem(ACCOUNTS_STORAGE_KEY)
    if (!accountsJson) {
      return []
    }

    try {
      const accounts = JSON.parse(accountsJson)
      return accounts.map((account: any) => ({
        ...account,
        expiresAt: account.expiresAt ? new Date(account.expiresAt) : undefined,
      }))
    } catch (error) {
      console.error("Failed to parse accounts:", error)
      return []
    }
  }

  // Get accounts by platform
  public getAccountsByPlatform(platform: SocialPlatform): SocialAccount[] {
    const accounts = this.getAccounts()
    return accounts.filter((account) => account.platform === platform)
  }

  // Get an account by ID
  public getAccount(id: string): SocialAccount | null {
    const accounts = this.getAccounts()
    const account = accounts.find((a) => a.id === id)
    return account || null
  }

  // Add a new account
  public addAccount(account: Omit<SocialAccount, "id">): SocialAccount {
    const accounts = this.getAccounts()
    const newAccount: SocialAccount = {
      ...account,
      id: `account-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
    }

    safeLocalStorage().setItem(ACCOUNTS_STORAGE_KEY, JSON.stringify([...accounts, newAccount]))
    return newAccount
  }

  // Update an account
  public updateAccount(id: string, updates: Partial<Omit<SocialAccount, "id">>): SocialAccount | null {
    const accounts = this.getAccounts()
    const index = accounts.findIndex((a) => a.id === id)

    if (index === -1) {
      return null
    }

    const updatedAccount: SocialAccount = {
      ...accounts[index],
      ...updates,
    }

    accounts[index] = updatedAccount
    safeLocalStorage().setItem(ACCOUNTS_STORAGE_KEY, JSON.stringify(accounts))
    return updatedAccount
  }

  // Remove an account
  public removeAccount(id: string): boolean {
    const accounts = this.getAccounts()
    const filteredAccounts = accounts.filter((a) => a.id !== id)

    if (filteredAccounts.length === accounts.length) {
      return false
    }

    safeLocalStorage().setItem(ACCOUNTS_STORAGE_KEY, JSON.stringify(filteredAccounts))
    return true
  }

  // Get all posts
  public getPosts(): SocialPost[] {
    const postsJson = safeLocalStorage().getItem(POSTS_STORAGE_KEY)
    if (!postsJson) {
      return []
    }

    try {
      const posts = JSON.parse(postsJson)
      return posts.map((post: any) => ({
        ...post,
        createdAt: new Date(post.createdAt),
      }))
    } catch (error) {
      console.error("Failed to parse posts:", error)
      return []
    }
  }

  // Get posts by platform
  public getPostsByPlatform(platform: SocialPlatform): SocialPost[] {
    const posts = this.getPosts()
    return posts.filter((post) => post.platform === platform)
  }

  // Get posts by account
  public getPostsByAccount(accountId: string): SocialPost[] {
    const posts = this.getPosts()
    return posts.filter((post) => post.accountId === accountId)
  }

  // Get posts by topic
  public getPostsByTopic(topicId: string): SocialPost[] {
    const topic = this.getTopic(topicId)
    if (!topic) {
      return []
    }

    const posts = this.getPosts()
    return posts.filter((post) => topic.posts.includes(post.id))
  }

  // Get a post by ID
  public getPost(id: string): SocialPost | null {
    const posts = this.getPosts()
    const post = posts.find((p) => p.id === id)
    return post || null
  }

  // Add a new post
  public addPost(post: Omit<SocialPost, "id" | "isBookmarked" | "topics">): SocialPost {
    const posts = this.getPosts()
    const newPost: SocialPost = {
      ...post,
      id: `post-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
      isBookmarked: false,
      topics: [],
    }

    safeLocalStorage().setItem(POSTS_STORAGE_KEY, JSON.stringify([...posts, newPost]))

    // Check if post matches any topics
    this.matchPostToTopics(newPost)

    return newPost
  }

  // Bookmark a post
  public bookmarkPost(id: string, isBookmarked = true): SocialPost | null {
    const posts = this.getPosts()
    const index = posts.findIndex((p) => p.id === id)

    if (index === -1) {
      return null
    }

    posts[index].isBookmarked = isBookmarked
    safeLocalStorage().setItem(POSTS_STORAGE_KEY, JSON.stringify(posts))
    return posts[index]
  }

  // Add a post to a topic
  public addPostToTopic(postId: string, topicId: string): boolean {
    const post = this.getPost(postId)
    const topic = this.getTopic(topicId)

    if (!post || !topic) {
      return false
    }

    // Update post topics
    const posts = this.getPosts()
    const postIndex = posts.findIndex((p) => p.id === postId)
    if (postIndex !== -1) {
      if (!posts[postIndex].topics.includes(topicId)) {
        posts[postIndex].topics.push(topicId)
      }
      safeLocalStorage().setItem(POSTS_STORAGE_KEY, JSON.stringify(posts))
    }

    // Update topic posts
    const topics = this.getTopics()
    const topicIndex = topics.findIndex((t) => t.id === topicId)
    if (topicIndex !== -1) {
      if (!topics[topicIndex].posts.includes(postId)) {
        topics[topicIndex].posts.push(postId)
      }
      safeLocalStorage().setItem(TOPICS_STORAGE_KEY, JSON.stringify(topics))
    }

    return true
  }

  // Remove a post from a topic
  public removePostFromTopic(postId: string, topicId: string): boolean {
    const post = this.getPost(postId)
    const topic = this.getTopic(topicId)

    if (!post || !topic) {
      return false
    }

    // Update post topics
    const posts = this.getPosts()
    const postIndex = posts.findIndex((p) => p.id === postId)
    if (postIndex !== -1) {
      posts[postIndex].topics = posts[postIndex].topics.filter((id) => id !== topicId)
      safeLocalStorage().setItem(POSTS_STORAGE_KEY, JSON.stringify(posts))
    }

    // Update topic posts
    const topics = this.getTopics()
    const topicIndex = topics.findIndex((t) => t.id === topicId)
    if (topicIndex !== -1) {
      topics[topicIndex].posts = topics[topicIndex].posts.filter((id) => id !== postId)
      safeLocalStorage().setItem(TOPICS_STORAGE_KEY, JSON.stringify(topics))
    }

    return true
  }

  // Delete a post
  public deletePost(id: string): boolean {
    const posts = this.getPosts()
    const filteredPosts = posts.filter((p) => p.id !== id)

    if (filteredPosts.length === posts.length) {
      return false
    }

    safeLocalStorage().setItem(POSTS_STORAGE_KEY, JSON.stringify(filteredPosts))

    // Remove post from topics
    const topics = this.getTopics()
    let topicsUpdated = false
    topics.forEach((topic, index) => {
      if (topic.posts.includes(id)) {
        topics[index].posts = topic.posts.filter((postId) => postId !== id)
        topicsUpdated = true
      }
    })

    if (topicsUpdated) {
      safeLocalStorage().setItem(TOPICS_STORAGE_KEY, JSON.stringify(topics))
    }

    return true
  }

  // Get all filters
  public getFilters(): SocialFilter[] {
    const filtersJson = safeLocalStorage().getItem(FILTERS_STORAGE_KEY)
    if (!filtersJson) {
      return []
    }

    try {
      const filters = JSON.parse(filtersJson)
      return filters.map((filter: any) => ({
        ...filter,
        dateRange: filter.dateRange
          ? {
              start: filter.dateRange.start ? new Date(filter.dateRange.start) : undefined,
              end: filter.dateRange.end ? new Date(filter.dateRange.end) : undefined,
            }
          : undefined,
      }))
    } catch (error) {
      console.error("Failed to parse filters:", error)
      return []
    }
  }

  // Get a filter by ID
  public getFilter(id: string): SocialFilter | null {
    const filters = this.getFilters()
    const filter = filters.find((f) => f.id === id)
    return filter || null
  }

  // Create a new filter
  public createFilter(filter: Omit<SocialFilter, "id">): SocialFilter {
    const filters = this.getFilters()
    const newFilter: SocialFilter = {
      ...filter,
      id: `filter-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
    }

    safeLocalStorage().setItem(FILTERS_STORAGE_KEY, JSON.stringify([...filters, newFilter]))
    return newFilter
  }

  // Update a filter
  public updateFilter(id: string, updates: Partial<Omit<SocialFilter, "id">>): SocialFilter | null {
    const filters = this.getFilters()
    const index = filters.findIndex((f) => f.id === id)

    if (index === -1) {
      return null
    }

    const updatedFilter: SocialFilter = {
      ...filters[index],
      ...updates,
    }

    filters[index] = updatedFilter
    safeLocalStorage().setItem(FILTERS_STORAGE_KEY, JSON.stringify(filters))
    return updatedFilter
  }

  // Delete a filter
  public deleteFilter(id: string): boolean {
    const filters = this.getFilters()
    const filteredFilters = filters.filter((f) => f.id !== id)

    if (filteredFilters.length === filters.length) {
      return false
    }

    safeLocalStorage().setItem(FILTERS_STORAGE_KEY, JSON.stringify(filteredFilters))

    // Remove filter from topics
    const topics = this.getTopics()
    let topicsUpdated = false
    topics.forEach((topic, index) => {
      if (topic.filters.includes(id)) {
        topics[index].filters = topic.filters.filter((filterId) => filterId !== id)
        topicsUpdated = true
      }
    })

    if (topicsUpdated) {
      safeLocalStorage().setItem(TOPICS_STORAGE_KEY, JSON.stringify(topics))
    }

    return true
  }

  // Apply a filter to posts
  public applyFilter(filter: SocialFilter, posts: SocialPost[]): SocialPost[] {
    return posts.filter((post) => {
      // Filter by platform
      if (filter.platforms.length > 0 && !filter.platforms.includes(post.platform)) {
        return false
      }

      // Filter by keywords
      if (filter.keywords.length > 0) {
        const content = post.content.toLowerCase()
        const hasKeyword = filter.keywords.some((keyword) => content.includes(keyword.toLowerCase()))
        if (!hasKeyword) {
          return false
        }
      }

      // Filter by authors
      if (filter.authors.length > 0) {
        const authorName = post.author.name.toLowerCase()
        const authorId = post.author.id.toLowerCase()
        const hasAuthor = filter.authors.some(
          (author) => authorName.includes(author.toLowerCase()) || authorId.includes(author.toLowerCase()),
        )
        if (!hasAuthor) {
          return false
        }
      }

      // Filter by excluded keywords
      if (filter.excludeKeywords.length > 0) {
        const content = post.content.toLowerCase()
        const hasExcludedKeyword = filter.excludeKeywords.some((keyword) => content.includes(keyword.toLowerCase()))
        if (hasExcludedKeyword) {
          return false
        }
      }

      // Filter by excluded authors
      if (filter.excludeAuthors.length > 0) {
        const authorName = post.author.name.toLowerCase()
        const authorId = post.author.id.toLowerCase()
        const hasExcludedAuthor = filter.excludeAuthors.some(
          (author) => authorName.includes(author.toLowerCase()) || authorId.includes(author.toLowerCase()),
        )
        if (hasExcludedAuthor) {
          return false
        }
      }

      // Filter by date range
      if (filter.dateRange) {
        const postDate = new Date(post.createdAt)
        if (filter.dateRange.start && postDate < filter.dateRange.start) {
          return false
        }
        if (filter.dateRange.end && postDate > filter.dateRange.end) {
          return false
        }
      }

      // Filter by sentiment
      if (filter.sentiment && filter.sentiment.length > 0 && post.sentiment) {
        if (!filter.sentiment.includes(post.sentiment)) {
          return false
        }
      }

      return true
    })
  }

  // Get all topics
  public getTopics(): SocialTopic[] {
    const topicsJson = safeLocalStorage().getItem(TOPICS_STORAGE_KEY)
    if (!topicsJson) {
      return []
    }

    try {
      const topics = JSON.parse(topicsJson)
      return topics.map((topic: any) => ({
        ...topic,
        lastChecked: topic.lastChecked ? new Date(topic.lastChecked) : undefined,
      }))
    } catch (error) {
      console.error("Failed to parse topics:", error)
      return []
    }
  }

  // Get a topic by ID
  public getTopic(id: string): SocialTopic | null {
    const topics = this.getTopics()
    const topic = topics.find((t) => t.id === id)
    return topic || null
  }

  // Create a new topic
  public createTopic(topic: Omit<SocialTopic, "id" | "posts">): SocialTopic {
    const topics = this.getTopics()
    const newTopic: SocialTopic = {
      ...topic,
      id: `topic-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
      posts: [],
    }

    safeLocalStorage().setItem(TOPICS_STORAGE_KEY, JSON.stringify([...topics, newTopic]))
    return newTopic
  }

  // Update a topic
  public updateTopic(id: string, updates: Partial<Omit<SocialTopic, "id" | "posts">>): SocialTopic | null {
    const topics = this.getTopics()
    const index = topics.findIndex((t) => t.id === id)

    if (index === -1) {
      return null
    }

    const updatedTopic: SocialTopic = {
      ...topics[index],
      ...updates,
    }

    topics[index] = updatedTopic
    safeLocalStorage().setItem(TOPICS_STORAGE_KEY, JSON.stringify(topics))
    return updatedTopic
  }

  // Delete a topic
  public deleteTopic(id: string): boolean {
    const topics = this.getTopics()
    const filteredTopics = topics.filter((t) => t.id !== id)

    if (filteredTopics.length === topics.length) {
      return false
    }

    safeLocalStorage().setItem(TOPICS_STORAGE_KEY, JSON.stringify(filteredTopics))

    // Remove topic from posts
    const posts = this.getPosts()
    let postsUpdated = false
    posts.forEach((post, index) => {
      if (post.topics.includes(id)) {
        posts[index].topics = post.topics.filter((topicId) => topicId !== id)
        postsUpdated = true
      }
    })

    if (postsUpdated) {
      safeLocalStorage().setItem(POSTS_STORAGE_KEY, JSON.stringify(posts))
    }

    // Delete drafts for this topic
    const drafts = this.getDrafts()
    const filteredDrafts = drafts.filter((d) => d.topicId !== id)
    if (filteredDrafts.length !== drafts.length) {
      safeLocalStorage().setItem(DRAFTS_STORAGE_KEY, JSON.stringify(filteredDrafts))
    }

    return true
  }

  // Match a post to topics
  public matchPostToTopics(post: SocialPost): string[] {
    const topics = this.getTopics()
    const matchedTopicIds: string[] = []

    topics.forEach((topic) => {
      if (!topic.isMonitoring) {
        return
      }

      // Check if post matches topic keywords
      const content = post.content.toLowerCase()
      const hasKeyword = topic.keywords.some((keyword) => content.includes(keyword.toLowerCase()))

      if (hasKeyword) {
        // Add post to topic
        this.addPostToTopic(post.id, topic.id)
        matchedTopicIds.push(topic.id)

        // Generate draft response if enabled
        if (topic.autoGenerateDrafts) {
          this.generateDraftResponse(post, topic)
        }
      }
    })

    return matchedTopicIds
  }

  // Get all drafts
  public getDrafts(): DraftResponse[] {
    const draftsJson = safeLocalStorage().getItem(DRAFTS_STORAGE_KEY)
    if (!draftsJson) {
      return []
    }

    try {
      const drafts = JSON.parse(draftsJson)
      return drafts.map((draft: any) => ({
        ...draft,
        createdAt: new Date(draft.createdAt),
      }))
    } catch (error) {
      console.error("Failed to parse drafts:", error)
      return []
    }
  }

  // Get drafts by topic
  public getDraftsByTopic(topicId: string): DraftResponse[] {
    const drafts = this.getDrafts()
    return drafts.filter((draft) => draft.topicId === topicId)
  }

  // Get drafts by status
  public getDraftsByStatus(status: "draft" | "approved" | "rejected" | "published"): DraftResponse[] {
    const drafts = this.getDrafts()
    return drafts.filter((draft) => draft.status === status)
  }

  // Get a draft by ID
  public getDraft(id: string): DraftResponse | null {
    const drafts = this.getDrafts()
    const draft = drafts.find((d) => d.id === id)
    return draft || null
  }

  // Generate a draft response
  public generateDraftResponse(post: SocialPost, topic: SocialTopic): DraftResponse {
    // In a real implementation, this would use an AI model to generate a response
    const draftContent = `This is a draft response to a post about "${topic.name}". The original post said: "${post.content.substring(
      0,
      50,
    )}..."`

    const draft: DraftResponse = {
      id: `draft-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
      topicId: topic.id,
      platform: post.platform,
      content: draftContent,
      createdAt: new Date(),
      status: "draft",
      postId: post.id,
      metadata: {
        originalPost: post,
      },
    }

    const drafts = this.getDrafts()
    safeLocalStorage().setItem(DRAFTS_STORAGE_KEY, JSON.stringify([...drafts, draft]))

    return draft
  }

  // Update a draft
  public updateDraft(id: string, updates: Partial<Omit<DraftResponse, "id" | "createdAt">>): DraftResponse | null {
    const drafts = this.getDrafts()
    const index = drafts.findIndex((d) => d.id === id)

    if (index === -1) {
      return null
    }

    const updatedDraft: DraftResponse = {
      ...drafts[index],
      ...updates,
    }

    drafts[index] = updatedDraft
    safeLocalStorage().setItem(DRAFTS_STORAGE_KEY, JSON.stringify(drafts))
    return updatedDraft
  }

  // Delete a draft
  public deleteDraft(id: string): boolean {
    const drafts = this.getDrafts()
    const filteredDrafts = drafts.filter((d) => d.id !== id)

    if (filteredDrafts.length === drafts.length) {
      return false
    }

    safeLocalStorage().setItem(DRAFTS_STORAGE_KEY, JSON.stringify(filteredDrafts))
    return true
  }

  // Fetch posts from a platform (mock implementation)
  public async fetchPosts(platform: SocialPlatform, accountId: string): Promise<SocialPost[]> {
    // In a real implementation, this would make API calls to the respective platforms
    // For now, we'll generate mock data
    const account = this.getAccount(accountId)
    if (!account) {
      throw new Error(`Account not found: ${accountId}`)
    }

    const mockPosts: Omit<SocialPost, "id" | "isBookmarked" | "topics">[] = []
    const now = new Date()

    // Generate 5-10 mock posts
    const count = Math.floor(Math.random() * 6) + 5
    for (let i = 0; i < count; i++) {
      const createdAt = new Date(now.getTime() - Math.random() * 86400000 * 7) // Random time in the last week

      const post: Omit<SocialPost, "id" | "isBookmarked" | "topics"> = {
        platform,
        accountId,
        author: {
          id: `author-${i}`,
          name: `User ${i} on ${platform}`,
          avatar: `/placeholder.svg?height=50&width=50`,
          url: `https://${platform}.com/user${i}`,
        },
        content: this.generateMockContent(platform),
        createdAt,
        likes: Math.floor(Math.random() * 100),
        shares: Math.floor(Math.random() * 50),
        comments: Math.floor(Math.random() * 20),
        sentiment: ["positive", "neutral", "negative"][Math.floor(Math.random() * 3)] as
          | "positive"
          | "neutral"
          | "negative",
        metadata: {
          source: platform,
          fetchedAt: new Date(),
        },
      }

      // Add media for some posts
      if (Math.random() > 0.6) {
        post.mediaUrls = [`/placeholder.svg?height=300&width=400`]
      }

      // Add URL
      post.url = `https://${platform}.com/post/${Date.now()}-${i}`

      mockPosts.push(post)
    }

    // Add posts to storage
    const addedPosts = mockPosts.map((post) => this.addPost(post))
    return addedPosts
  }

  // Generate mock content based on platform
  private generateMockContent(platform: SocialPlatform): string {
    const topics = [
      "artificial intelligence",
      "machine learning",
      "web development",
      "blockchain",
      "cryptocurrency",
      "climate change",
      "renewable energy",
      "space exploration",
      "quantum computing",
      "virtual reality",
    ]

    const selectedTopic = topics[Math.floor(Math.random() * topics.length)]

    switch (platform) {
      case "twitter":
        return `Just read an amazing article about ${selectedTopic}! The future is now. #tech #innovation`
      case "facebook":
        return `I've been researching ${selectedTopic} lately and I'm amazed by the progress we're making. What do you all think about the recent developments in this field?`
      case "instagram":
        return `Exploring the world of ${selectedTopic} today. So much to learn! 📚 #learning #technology`
      case "linkedin":
        return `Excited to share my thoughts on the future of ${selectedTopic}. This technology is transforming industries and creating new opportunities for innovation.`
      case "youtube":
        return `NEW VIDEO: "Understanding ${selectedTopic} in 10 Minutes" - Check out my latest explainer video where I break down this complex topic!`
      case "reddit":
        return `[Discussion] What's your take on the ethical implications of ${selectedTopic}? I've been thinking about this a lot lately and would love to hear different perspectives.`
      case "discord":
        return `Hey everyone! I found this cool resource about ${selectedTopic}. Has anyone else checked it out?`
      case "github":
        return `Fixed a critical bug in the ${selectedTopic} implementation. This should improve performance by ~30%.`
      case "telegram":
        return `New group for discussing ${selectedTopic}! Join us at t.me/${selectedTopic.replace(/\s+/g, "")}`
      case "twitch":
        return `Going live in 10 minutes to talk about ${selectedTopic}! Don't miss it!`
      case "pinterest":
        return `10 Amazing ${selectedTopic} Projects You Can Do at Home | DIY Technology`
      case "notion":
        return `## ${selectedTopic.toUpperCase()} RESEARCH\n\nKey findings:\n- Rapid growth in adoption\n- New frameworks emerging\n- Potential for disruption in multiple industries`
      default:
        return `Interesting developments in ${selectedTopic} lately. What are your thoughts?`
    }
  }
}

// Export a singleton instance
export const socialMediaService = new SocialMediaService()
